python run_mr.py \
--model_type=bert \
--model_name_or_path="../splinter" \
--qass_head=True \
--tokenizer_name="../splinter" \
--output_dir="output" \
--train_file="../mrqa-few-shot/squad/squad-train-seed-42-num-examples-16_qass.jsonl" \
--predict_file="../mrqa-few-shot/squad/dev_qass.jsonl" \
--do_train \
--do_eval \
--max_seq_length=384 \
--doc_stride=128 \
--threads=1 \
--save_steps=50000 \
--per_gpu_train_batch_size=12 \
--per_gpu_eval_batch_size=16 \
--learning_rate=3e-5 \
--max_answer_length=10 \
--warmup_ratio=0.1 \
--min_steps=200 \
--num_train_epochs=10 \
--seed=42 \
--use_cache=False \
--evaluate_every_epoch=False \
--initialize_new_qass=False \
--overwrite_output_dir